/* OPDEF (OPCODE, OPNAME, name_zenglj, OPKIND, operand_count), 其中：
    OPNAME 是操作码的名称。
    OPCODE 是操作码值。
    OPKIND 是操作的类型。 */

OPDEF (nop,           "nop",   "undef", 0,           0)
OPDEF (load,          "load",  "=",     LOAD,        2)
OPDEF (aload,         "aload", "undef", LOAD|ARRAY,  3)
OPDEF (store,         "store", "=",     STORE,       2)
OPDEF (astore,        "astore","undef", STORE|ARRAY, 4)
OPDEF (move,          "move",  "=",     UNOP,        2)
OPDEF (add,           "add",   "add",   BINOP,       3)
OPDEF (addptr,        "addptr","add",   BINOP,       4)
OPDEF (sub,           "sub",   "sub",   BINOP,       3)
OPDEF (mul,           "mul",   "mul",   BINOP,       3)
OPDEF (div,           "div",   "div",   BINOP,       3)
OPDEF (rem,           "rem",   "mod",   BINOP,       3)
OPDEF (lsl,           "lsl",   "undef", BINOP,       3)
OPDEF (asr,           "asr",   "undef", BINOP,       3)
OPDEF (lsr,           "lsr",   "undef", BINOP,       3)
OPDEF (neg,           "neg",   "neg",   UNOP,        2)
OPDEF (i2f,           "i2f",   "itof",  UNOP|CONVERT,2)
OPDEF (f2i,           "f2i",   "ftoi",  UNOP|CONVERT,2)
OPDEF (ifeq,          "ifeq",  "cmp eq",BRANCH,      4)
OPDEF (ifne,          "ifne",  "cmp ne",BRANCH,      4)
OPDEF (iflt,          "iflt",  "cmp lt",BRANCH,      4)
OPDEF (ifge,          "ifge",  "cmp ge",BRANCH,      4)
OPDEF (ifgt,          "ifgt",  "cmp gt",BRANCH,      4)
OPDEF (ifle,          "ifle",  "cmp le",BRANCH,      4)
OPDEF (eq,            "eq",    "undef", BINOP,       3)
OPDEF (ne,            "ne",    "undef", BINOP,       3)
OPDEF (lt,            "lt",    "undef", BINOP,       3)
OPDEF (ge,            "ge",    "undef", BINOP,       3)
OPDEF (gt,            "gt",    "undef", BINOP,       3)
OPDEF (le,            "le",    "undef", BINOP,       3)
OPDEF (not,           "not",   "undef", UNOP,        2)
OPDEF (goto,          "goto",  "br",    BRANCH,      1)
OPDEF (call,          "call",  "call",  INVOKE,      3)
OPDEF (param,         "param", "arg",   SPECIAL,     1)
OPDEF (fparam,        "fparam","undef", SPECIAL,     1)
OPDEF (entry,         "entry", "entry", SPECIAL,     1)
OPDEF (exit,          "exit",  "exit",  SPECIAL,     1)
OPDEF (phi,           "phi",   "undef", SPECIAL,     1)

OPDEF (begin_block,   "begin_block","undef", SPECIAL,     1)
OPDEF (end_block,     "end_block","undef", SPECIAL,     1)
